import heapq
a = list(map(int,input().split()))
heapq.heapify(a)
print(a)
b = int(input())
heapq.heappush(a, b)
print(a)
heapq.heappop(a)
print(a)
c = int(input())
heapq.heappushpop(a, c)
print(a)
d = int(input())
heapq.heapreplace(a, d)
